services:
  client:
    build: ./client
    container_name: angular
    ports:
      - "4200:8080"
    depends_on:
      - server
    networks:
      - express-network

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - express-network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: rigel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - rigel-data:/var/lib/postgresql/data
      - ./server/postgres-init:/docker-entrypoint-initdb.d
    networks:
      - express-network

volumes:
  rigel-data:

networks:
  express-network:
    driver: bridge
